- notebooks/omgmega_example.ipynb
- qdax/core/emitters/omg_mega_emitter.py
- tests/core_test/omgmega_test.py
Related to issue [#19](https://github.com/adaptive-intelligent-robotics/QDax/issues/19)
This PR adds OMG MEGA (Objective and Measure Gradient MAP-Elites via Gradient Arborescence), a baseline from the paper [Differentiable Quality Diversity](https://arxiv.org/pdf/2106.03894.pdf).
In this algorithm, one suppose access to the derivatives of the scoring function (fitness and behavior descriptor).
**Future improvement:**
Double addition in the archive: in this implementation, in order to fit into the actual design of MAP-Elites, we have to compute the addition in the grid two times. As a matter of fact, gradients are stored in a grid repertoire, just like the genotypes, and when the scoring is made, the gradients are updated in the gradients repertoire just like it has been made in the …
> Add the algorithm OMG-MEGA to QDax

- dev.Dockerfile
- environment.yaml
- qdax/core/containers/repertoire.py
- qdax/core/emitters/pga_me_emitter.py
- requirements.txt
This PR updates several requirements. It was initially created to address the GitHub dependabot security issue to do with the numpy version. 
It also increases the jax version to 0.3.10
**Notes:**
- the performances where quickly checked with a few seeds on PGAME but in the future it is important that we set up a way to check up the performance of most of the algorithms on several environments to make sure the performance is not impacted by version changes (and also by usual PRs)
- this PR has the same commits as #26, they were basically cherry-picked to have a branch out and in develop instead of master
> Update requirements: upgrade numpy and jax

- notebooks/cmamega_example.ipynb
- notebooks/diayn_example.ipynb
- notebooks/mapelites_example.ipynb
- notebooks/mome_example.ipynb
- notebooks/omgmega_example.ipynb
- notebooks/pgame_example.ipynb
- notebooks/smerl_example.ipynb
- qdax/core/containers/repertoire.py
- tests/core_test/cmamega_test.py
- tests/core_test/map_elites_test.py
- tests/core_test/mome_test.py
- tests/core_test/pgame_test.py
The `compute_cvt_centroids(...)` function is the only function in the code that relies on `numpy.random` (and not `jax.random`) to generate random points and run a k-means.
This PR modifies `compute_cvt_centroids(...)` to use the `jax.random` module instead of `numpy.random`, in order to stay consistent in the usage of random number generators.
> Using RNGKey for sampling CVT centroids and for KMeans

- .github/workflows/ci.yaml
The current CI has redundancies, when a pull request is opened, both push and pull request events are true and the jobs are hence launched two times. 
In this PR, a new rule is suggested. The CI would be triggered when:
- a push is made on develop or main
- a pull request is opened (even as a draft)
Hence, a branch that does not correspond yet to a PR will not trigger any CI action.
> Update the rules that trigger the CI

- qdax/core/containers/mome_repertoire.py
- qdax/core/containers/repertoire.py
- qdax/core/sac.py
- qdax/core/td3.py
- tests/core_test/map_elites_test.py
- tests/core_test/mome_test.py
This PR aims to fix the container addition for 1D-BD tasks. With the current container implementation, 1D-BD tasks such as the Hopper-uni task for example (`hopper_uni`) returns the following error:
This is due to the `squeeze` of the descriptors done in the `add()` method of the repertoire. These `squeeze` are necessary for the fitnesses and indices as these arrays are explicitly `expand_dims` at the beginning of the `add()` method. However it is not needed for the descriptors that are not modified in the `add()` method.
Thus as a fix I propose to remove the `squeeze` for the descriptors. 
This change should not impact the results, but just in case I attached the experimental comparison on GPU with the original container implementation and the new proposed container implementation on the …
> fix: remove descriptors squeeze() to fix 1D-BD tasks

- qdax/utils/plotting.py
- tests/utils_test/plotting_test.py
Adding a function `plot_multidimensional_map_elites_grid` for showing grids when the dimensionality of the descriptors is greater than 2.
Here are some examples of plots that are generated:
- for a `grid_shape` of `(4, 4, 2)` (with `dimensionality_descriptors=3`)
- for a `grid_shape` of `(4, 4, 4, 4, 4, 4)` (with `dimensionality_descriptors=6`)
Here is some code for testing it:
```python
dimensionality_descriptors = 3
grid_shape = (4, 4, 2)
minval = jnp.array([0] * dimensionality_descriptors)
maxval = jnp.array([1] * dimensionality_descriptors)
random_key = jax.random.PRNGKey(seed=0)
random_key, key_desc, key_fit = jax.random.split(random_key, num=3)
number_samples_test = 300
descriptors = jax.random.uniform(key_desc, shape=(number_samples_test, dimensionality_descriptors))
fitnesses = …
```
> Adding plot_multidimensional_map_elites_grid function

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- docs/installation.md
- mkdocs.yml
- singularity/build_final_image
- singularity/build_final_image.py
- singularity/singularity.def
- singularity/start_container
- singularity/start_container.py
- tests/core_test/map_elites_test.py
- tests/environments_test/pointmaze_test.py
This PR updates the Singularity pipeline to allow any user to build and use final and sandbox Singularity containers for this repo.
In particular it:
- fixes the singularity scripts to fulfil the style requirement
- replaces the local base image that was not publicly available with an online base image [hosted on Sylabs](https://cloud.sylabs.io/library/airl_lab/default/airl_env) and containing all the required library 
- simplifies the singularity.def
- adds the singularity pipeline to the documentation
> Update Singularity pipeline

- .github/workflows/ci.yaml
- README.md
- requirements-dev.txt
This PR adds codecov to QDax.
This enables to have tests reports and track the code covered by our tests.
**Notes:**
- change the link before merging in develop (and same for master in the future)
- would be nice to change the badge link for every branch (automatically)
- the upload works but the codecov interface still shows issues
> Adding codecov to QDax for test coverage reports

- notebooks/cmamega_example.ipynb
- notebooks/dads_example.ipynb
- notebooks/diayn_example.ipynb
- notebooks/mapelites_example.ipynb
- notebooks/mome_example.ipynb
- notebooks/omgmega_example.ipynb
- notebooks/pgame_example.ipynb
- notebooks/smerl_example.ipynb
This PR just adds the 'Open in Colab' to the top of all the example notebooks to make it easier to run the code.
> Add 'Open in Colab' link to all example notebooks

- notebooks/cmamega_example.ipynb
- notebooks/dads_example.ipynb
- notebooks/diayn_example.ipynb
- notebooks/mapelites_example.ipynb
- notebooks/mome_example.ipynb
- notebooks/nsga2_spea2_example.ipynb
- notebooks/omgmega_example.ipynb
- notebooks/pgame_example.ipynb
- notebooks/smerl_example.ipynb
This PR remove the autoreloads in the notebooks and pin the brax version to v0.0.12
> Pin brax version in notebooks + remove autoreload

- README.md
This PR fixes one of the links to the example notebook in the README
> fix colab notebook link in README

- README.md
- setup.py
- changing installation instructions to `pip install qdax`
- changing development status in `setup.py` to `4 - Beta`
The package website should look like this (without the changes mentioned above): [https://test.pypi.org/project/qdax/](https://test.pypi.org/project/qdax/)
> Update README and setup.py for pypi

- qdax/core/neuroevolution/losses/td3_loss.py
As recently discussed with the development team, there was a slight error in the loss of TD3. 
This PR updates the loss to correct it.
> fix: correct irrelevant factor 0.25 in td3 loss

- tests/utils_test/sampling_test.py
Fix `sampling_test.py`, in which the name of fitnesses and descriptors are inverted. The test is still correct, this is only a naming issue.
> fix: sampling_test incorrect naming

- .dockerignore
- dev.Dockerfile
This PR fixes the `run-image` of the `dev.Dockerfile` by copying the` README.md `into the docker container (which requires removing `README.md` from the `.dockerignore`). Closes #96.
> fix: run-image

- qdax/environments/__init__.py
Fix the order in which we are applying the wrappers to make sure that state descriptors are in line with fixed init states.
Without this modification, FixedInitialStateWrapper is overwriting state.obs without changing the state descriptor accordingly.
> Fix state descriptors in case fixed init states are used

- qdax/environments/__init__.py
Necessary to make sure that the state descriptors are also updated when using a fixed initial state with the wrapper
> Fixing the order of wrappers in env create function

- requirements.txt
- setup.py
switched depreciated dependency sklearn -> scikit-learn
Related issues: #130
The PR replaces the depreciated `sklearn` package with `scikit-learn`.
N/A
> switched depreciated dependency sklearn -> scikit-learn

- examples/dads.ipynb
- examples/diayn.ipynb
- examples/me_sac_pbt.ipynb
- examples/sac_pbt.ipynb
- examples/smerl.ipynb
- qdax/baselines/dads.py
- qdax/baselines/diayn.py
- qdax/baselines/sac.py
- qdax/baselines/sac_pbt.py
- qdax/core/neuroevolution/networks/dads_networks.py
- qdax/core/neuroevolution/networks/diayn_networks.py
- qdax/core/neuroevolution/networks/sac_networks.py
- tests/baselines_test/dads_smerl_test.py
- tests/baselines_test/dads_test.py
- tests/baselines_test/diayn_smerl_test.py
- tests/baselines_test/diayn_test.py
- tests/baselines_test/me_pbt_sac_test.py
- tests/baselines_test/pbt_sac_test.py
- tests/baselines_test/sac_test.py
This PR is to try to make the Deep RL algorithms more uniform. It allows the SAC, DIAYN and DADS implementation to have separate policy (actor) and critic architectures, as is already the case in the TD3 implementation. This allows more flexibility and is needed sometimes for comparison with QD algorithms which do not necessarily have a critic which needs a bigger size while the actor can be smaller.
This PR changes:
- the hidden_layer_sizes to policy_hidden_layer_size and critic_hidden_layer_size for SAC, DIAYN and DADS
for DADS and DIAYN there is also the discriminator or dynamics architecture to expose. For now it is set to the critic architecture
> chore: uniform sac network sizes

- README.md
- docs/api_documentation/core/mels.md
- examples/mels.ipynb
- mkdocs.yml
- qdax/core/containers/mels_repertoire.py
- qdax/core/mels.py
- qdax/types.py
- qdax/utils/sampling.py
- tests/core_test/containers_test/mels_repertoire_test.py
- tests/core_test/mels_test.py
This PR is a local clone of #152, just to double check for potential style issues
* Add MELS Repertoire 
* Create MELS Algorithm class
* Introduce Spread type
* Add multi_sample_scoring_function
Authored-by: b-tjanaka@wings <b.tjanaka@instadeep.com>
[List here potential observations made and/or improvements that could be made in the future. If relevant, open issues for those.]
> feat(algo): Add MAP-Elites Low-Spread (#152)

- .github/workflows/ci.yaml
- README.md
- examples/jumanji_snake.ipynb
- qdax/environments/__init__.py
- qdax/environments/wrappers.py
- tests/default_tasks_test/jumanji_envs_test.py
- tests/environments_test/pointmaze_test.py
- tests/environments_test/wrapper_test.py
- Fixes the bugs of imports in the `develop` branch.
- Fix formatting issues in `develop`.
> Fix imports jumpy and formatting issues

- qdax/utils/pareto_front.py
This PR:
-  Fixes the definition of Pareto dominance in `pareto_front.py` to account for solutions which have the same fitness values along one axis.
> Fix pareto dominance definition

- qdax/types.py
Related issues: N/A
Fix a bug in `types.py` script, `jax.random.KeyArray` is deprecated in JAX and should be replaced by `jax.Array`.
n/a
> Change deprecated jax type

- docs/guides/CONTRIBUTING.md
Related issues: #170 
Adding a few sentences to better explain the contribution process. In particular, made it clear that one needs to start by opening a github issue, then fork the repository (unless having permission to branch inside the main project), and request to merge to develop once the contribution is ready.
n/a
> Update the contribution guide in the documentation

- qdax/utils/uncertainty_metrics.py
- tests/utils_test/uncertainty_metrics_test.py
Add reevaluation function to compute corrected archives in uncertain domains (see https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10120985)
This PR introduces:
- A new file qdax/utils/uncertain_metrics.py that defines two reevaluation functions to compute the corrected archive for uncertain domains. 
- The corresponding test function tests/utils_test/uncertainty_metrics_test.py.
> feat: add reevaluation function to compute corrected archives in uncertain domains

- requirements.txt
- setup.py
Related issues: #205 
Removing the following useless dependencies from requirements.txt:
- `gym`
- `ipython`
- `jupyter`
N/A sufficient tests have been written
N/A relevant section added to the documentation
N/A example notebook added to the repo
N/A clean docstrings and comments have been written
N/A if any issue/observation has been discovered, a new issue has been opened
> Hotfix: remove useless dependencies (including gym dependency)

- qdax/core/emitters/dcrl_emitter.py
- qdax/core/emitters/dpg_emitter.py
- qdax/core/emitters/qpg_emitter.py
- qdax/core/neuroevolution/losses/td3_loss.py
Related issues: PGA and DCRL: duplicated sampling of transitions in "emit_pg", unnecessary occupation of Vram in "state_update", too complicated structure of functions.
This PR introduces:
- Off-springs performing PG mutation now share the same mini-batch of data in emit_pg. 
- Sampling of transitions in both "emit_pg" and "state_update" is now made step by step. 
- "policy_loss" in "make_td3_dc_loss" now take desc_prime from the input instead of from transitions (so that transition can be shared) .
- Function "mutate_function_pg" is simplified and emerged into "emit_pg".
- Combined "train_xxxx" and "update_xxxx" into a single function.
- Build a new function "scan_actor_critic_training" for Actor-Critic training loop.
- Removed meaningless similarity (and novelty) calculation in …
> Feature vram opt

- qdax/utils/plotting.py
Related issues: plot_map_elites_results does not allow to use generations or episodes as x label
This PR introduces:
- Custom x_label field in plot_map_elites_results
- defaults to Environment steps
- I did not change the name of the env_steps field to avoid breaking changes
- [NA] sufficient tests have been written
- [NA] example notebook have been added to the repo
- [NA] all example notebooks have been verified to execute without errors
- Change env_steps to x_axis, x_data or logging_steps?
> Custom x label for plotting
